-- MySQL Script generated by MySQL Workbench
-- Wed May 24 13:03:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestion_liens
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestion_liens
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion_liens` DEFAULT CHARACTER SET utf8 ;
USE `gestion_liens` ;

-- -----------------------------------------------------
-- Table `gestion_liens`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_liens`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `forename` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `user_mail` VARCHAR(200) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `avatar` BLOB NOT NULL,
  `avatar_type_mime` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_mail_UNIQUE` (`user_mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_liens`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_liens`.`tags` (
  `tag_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `color` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_liens`.`links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_liens`.`links` (
  `link_id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(500) NOT NULL,
  `title` VARCHAR(20) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `creation-date` DATETIME NOT NULL,
  `id_user` INT NOT NULL,
  `id_tag` INT NOT NULL,
  PRIMARY KEY (`link_id`),
  INDEX `FK1_idx` (`id_user` ASC) VISIBLE,
  INDEX `FK4_idx` (`id_tag` ASC) VISIBLE,
  CONSTRAINT `FK1`
    FOREIGN KEY (`id_user`)
    REFERENCES `gestion_liens`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK4`
    FOREIGN KEY (`id_tag`)
    REFERENCES `gestion_liens`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_liens`.`links_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_liens`.`links_tags` (
  `id_link` INT NOT NULL,
  `id_tag` INT NOT NULL,
  INDEX `FK2_idx` (`id_link` ASC) VISIBLE,
  INDEX `FK3_idx` (`id_tag` ASC) VISIBLE,
  CONSTRAINT `FK2`
    FOREIGN KEY (`id_link`)
    REFERENCES `gestion_liens`.`links` (`link_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK3`
    FOREIGN KEY (`id_tag`)
    REFERENCES `gestion_liens`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_liens`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_liens`.`likes` (
  `id_user` INT NOT NULL,
  `id_link` INT NOT NULL,
  INDEX `FK5_idx` (`id_user` ASC) VISIBLE,
  INDEX `FK6_idx` (`id_link` ASC) VISIBLE,
  CONSTRAINT `FK5`
    FOREIGN KEY (`id_user`)
    REFERENCES `gestion_liens`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK6`
    FOREIGN KEY (`id_link`)
    REFERENCES `gestion_liens`.`links` (`link_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
